[theme]
# Couleur primaire pour les éléments interactifs
primaryColor="#0068C9" # Un bleu professionnel

# Couleur de fond principale
backgroundColor="#F0F2F6" # Un gris très clair et doux

# Couleur de fond de la sidebar
secondaryBackgroundColor="#FFFFFF" # Blanc pur pour la sidebar

# Couleur du texte
textColor="#1A1A1A" # Un noir doux

# Police de caractères
font="sans serif"